### ISSUE TITLE
Multiple test failures

### ISSUE THREAD

**Issue by telans** [vincentdephily/emlop#15]
From what I can see it appears to be mostly related to date/tz conversion. `predict_tty` seems to fail due to the test checking for the wrong output. `predict_tty` checks for `No pretended merge found`, but the command that is run outputs `No ongoing merge found` as it is called without parsing logs through a pipe.

https://dpaste.com/8ZPP9N73K.txt

See https://bugs.gentoo.org/784008

**Comment by vincentdephily** [comment]
Thanks for the report, sorry for only noticing it now. The failures in the Gentoo bugreport are slightly different from yours. I can't immediately reproduce those errors but I'll dig a bit.

I'm guessing the local timezone might explain some failures. Can you paste the output of `locales` and `cat /etc/timezone` ?

Looking at your predict_tty failure it is trying to read the system's `/var/log/emerge.log`. That should be easy to fix, but that doesn't match your description... ?

Note that some tests will fail if there actually is an ongoing merge, which seemed fair game to me, but I realize in going to be a showstopper for `USE=test`.

**Comment by vincentdephily** [comment]
@telans I believe the current master branch fixes all test failures, could you `git pull && cargo test -- --include-ignored` ?

**Comment by vincentdephily** [comment]
I've released 0.4.2 with all the fixes.
AFAICT this bug is fixed, but please reopen it (or create a new one) if necessary.
Thanks.
