### ISSUE TITLE
`start_time` unittest fails with unexpected `ps` output

### ISSUE THREAD

**Issue by vincentdephily** [vincentdephily/emlop#20]
Split off from #19 

---- proces::tests::start_time stdout ----
thread 'proces::tests::start_time' panicked at 'Couldn't parse   PID                  STARTED', src/proces.rs:130:29

@flexibeast what's your version of `ps` ? Mine (sys-process/procps-3.3.17-r1) doesn't output headers with the given options, but looking at the manpage it looks like `--no-headers` would be more safer than `-h`.

**Comment by vincentdephily** [comment]
There's a tentative fix in https://github.com/vincentdephily/emlop/commit/f708d93008f51a263734ca79a72837235d782558 please check.

**Comment by flexibeast** [comment]
3.3.17-r1 for me also.

Yes, that seems to have worked:

```
test proces::tests::start_time ... ok
```
