### ISSUE TITLE
`emlop l -ss` doesn't show latest sync operations if using `emaint sync -a` instead of `emerge --sync` or `eix-sync`

### ISSUE THREAD

**Issue by xfzv** [vincentdephily/emlop#41]
```console
❯ emlop -V
emlop 0.6.1   # Installed from Gentoo repo
```

To reproduce:

1. Run `# emerge --sync`
2. Run `$ emlop l -ss -n 10`
3. Latest dates for each repo sync are correct
4. Run `# eix-sync`
5. Run `$ emlop l -ss -n 10`
6. Latest dates for each repo sync are correct as well
7. Run `# emaint sync -a`
8. Run `$ emlop l -ss -n 10` again
9. Dates for each repo sync haven't changed, those from `# eix-sync` are still the latest

From [Gentoo Wiki - Repository_synchronization](https://wiki.gentoo.org/wiki/Ebuild_repository#Repository_synchronization):

> The **emerge --sync** command is now only a compatibility command. Primary control of all sync operations has been moved from **emerge** to **emaint**, and **emerge --sync** now just calls the emaint sync module with the `--auto` option. This performs a sync on only those repositories with the auto-sync setting set to `yes` or `true`. If the auto-sync option is _not_ set or is absent for the configured repositories, then **emerge --sync** may sync no repositories at all.

---

**Edit:** I'm actually getting the same behavior with `qlop -s`.

I wonder why none of the sync operations are parsed when using `emaint`.

**Edit 2:** Turns out `# emaint sync -a` doesn't write anything to `/var/log/emerge.log`, unlike `# emerge --sync` or `# eix-sync`.

Closing as this is irrelevant, there is nothing wrong with `emlop`.

**Comment by vincentdephily** [comment]
Thanks for the heads up anyway, I wasn't aware of this issue. Bug comment suggests the fix shouldn't be too complex, but need to dive into portage.
